baseURL = 'https://izzyandjonny.co.uk/'
languageCode = 'en-GB'
title = 'Isabelle and Jonathan'

[params]
  [params.wedding]
    date = "May 4, 2024 13:30:00"
    #registry = "https://weddingshop.com/giftlist/izzyandjonny"
    rsvps = false
