baseURL = 'https://izzyandjonny.co.uk/'
languageCode = 'en-GB'
title = 'Isabelle and Jonathan'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.wedding]
    enableRegistry = true
    registry = "https://prezola.com/wishlists/10288428/"
