baseURL = 'https://izzyandjonny.co.uk/'
languageCode = 'en-GB'
title = 'Isabelle and Jonathan'

[params]
  [params.wedding]
    enableRegistry = true
    registry = "https://weddingshop.com/giftlist/izzyandjonny"
