baseURL = 'https://izzyandjonny.co.uk/'
languageCode = 'en-GB'
title = 'Isabelle and Jonathan'

[params]
  [params.wedding]
    longdate = "4th May 2024"
    shortdate = "04.05.2022"
    enableRegistry = false
    registry = "https://weddingshop.com/giftlist/izzyandjonny"
    rsvps = false
    rsvpUrl = "https://forms.gle/7bvemVDeTT1YqNTBA"
